---
version: '3.8'

services:
  postgres:
    image: postgres:14.2
    shm_size: 1gb
    environment:
      POSTGRES_DB: loyalty
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
  server:
    build: ./
    restart: always
    entrypoint: ["/app/bin/server"]
    environment:
      LOG_LEVEL: "DEBUG"
      DATABASE_URI: "postgres://dbuser:dbpass@postgres:5432/loyalty"
      RUN_ADDRESS: "0.0.0.0:8080"
      ACCRUAL_SYSTEM_ADDRESS: "tests:8081"
    ports:
      - "8080:8080"
  tests:
    build: ./tests
    entrypoint:
     - "gophermarttest"
     - "-test.v"
     - "-test.run=^TestGophermart$$"
     - "-gophermart-binary-path=bin/true"
     - "-gophermart-host=server"
     - "-gophermart-port=8080"
     - '-gophermart-database-uri="postgres://dbuser:dbpass@postgres:5432/loyalty"'
     - "-accrual-binary-path=/usr/bin/accrual"
     - "-accrual-host=0.0.0.0"
     - "-accrual-port=8081"
     - '-accrual-database-uri="postgres://dbuser:dbpass@postgres:5432/loyalty"'
    environment:
      LOG_LEVEL: "DEBUG"
