---
version: '3.8'

services:
  postgres:
    image: postgres:14.2
    shm_size: 1gb
    environment:
      POSTGRES_DB: loyalty
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
  statictests:
    build: ./
    entrypoint: "bash -c 'go vet -vettool=/usr/bin/statictest $$(go list ./... | grep -v migrations)'"
  tests:
    build: ./
    entrypoint:
     - "gophermarttest"
     - "-test.v"
     - "-test.run=^TestGophermart$$"
     - "-gophermart-binary-path=/app/bin/server"
     - "-gophermart-host=localhost"
     - "-gophermart-port=8080"
     - "-gophermart-database-uri=postgres://dbuser:dbpass@postgres:5432/loyalty"
     - "-accrual-binary-path=/usr/bin/accrual"
     - "-accrual-host=localhost"
     - "-accrual-port=8081"
     - "-accrual-database-uri=postgres://dbuser:dbpass@postgres:5432/loyalty"
    environment:
      LOG_LEVEL: "ERROR"
