---
version: '3.8'

services:
  postgres:
    image: postgres:14.2
    shm_size: 1gb
    environment:
      POSTGRES_DB: loyalty
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
  server:
    build: ./
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      RUN_ADDRESS: "0.0.0.0:8080"
      DATABASE_URI: "postgres://dbuser:dbpass@postgres:5432/loyalty"
      LOG_LEVEL: "DEBUG"
  statictests:
    profiles: ["tests"]
    build: ./
    entrypoint: "bash -c 'go vet -vettool=/usr/bin/statictest ./...'"
  tests:
    profiles: ["tests"]
    build: ./
    entrypoint:
     - "gophermarttest"
     - "-test.v"
     - "-test.run=^TestGophermart$$"
     - "-gophermart-binary-path=/app/bin/server"
     - "-gophermart-host=localhost"
     - "-gophermart-port=8080"
     - "-gophermart-database-uri=postgres://dbuser:dbpass@postgres:5432/loyalty"
     - "-accrual-binary-path=/usr/bin/accrual"
     - "-accrual-host=localhost"
     - "-accrual-port=8081"
     - "-accrual-database-uri=postgres://dbuser:dbpass@postgres:5432/loyalty"
    environment:
      LOG_LEVEL: "DEBUG"
