---
name: gophermart

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  gophermarttest:
    runs-on: ubuntu-latest
    container: golang:1.17

    env:
      DATABASE_URI: "postgresql://postgres:postgres@postgres/praktikum?sslmode=disable"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: praktikum
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download autotests binaries
        uses: robinraju/release-downloader@v1.2
        with:
          repository: Yandex-Practicum/go-autotests-bin
          latest: true
          fileName: "*"
          out-file-path: .tools

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools
          mv $GITHUB_WORKSPACE/.tools/gophermarttest /usr/local/bin/gophermarttest
          mv $GITHUB_WORKSPACE/.tools/random /usr/local/bin/random

      - name: Build binaries
        run: |
          (make build)
          (curl -L -o accrual https://github.com/yandex-praktikum/go-musthave-diploma-tpl/raw/master/cmd/accrual/accrual_linux_amd64)
          (chmod +x accrual)
          (go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest)

      - name: Run migrations
        run: |
          migrate -source file://db/migrations -database $DATABASE_URI up

      - name: Test
        run: |
          gophermarttest \
            -test.v -test.run=^TestGophermart$ \
            -gophermart-binary-path=$GITHUB_WORKSPACE/bin/server \
            -gophermart-host=localhost \
            -gophermart-port=8080 \
            -gophermart-database-uri=$DATABASE_URI \
            -accrual-binary-path=$GITHUB_WORKSPACE/accrual \
            -accrual-host=localhost \
            -accrual-port=$(random unused-port) \
            -accrual-database-uri=$DATABASE_URI
